apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduhamuy-web
  labels:
    app: eduhamuy-web
spec:
  replicas: 1

  selector:
    matchLabels:
      app: eduhamuy-web

  template:
    metadata:
      labels:
        app: eduhamuy-web

    spec:
      imagePullSecrets:
        - name: ghcr-eduhamuy
      containers:
        - name: eduhamuy-web
          image: ghcr.io/eduhamuy/eduhamuy-web:dev

          ports:
            - containerPort: 3000
              protocol: TCP

          env:
            - name: NODE_ENV
              value: production

            - name: PORT
              value: "3000"

            - name: HOSTNAME
              value: "0.0.0.0"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"