apiVersion: v1
kind: Service
metadata:
  name: eduhamuy-web
  labels:
    app: eduhamuy-web

spec:
  type: ClusterIP

  selector:
    app: eduhamuy-web

  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP