apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eduhamuy-dev

resources:
  - ../../../apps/eduhamuy-web/base
  - httproute.yaml
  - http-redirect.yaml

patches:
  - path: deployment-env.yaml

images:
  - name: ghcr.io/eduhamuy/eduhamuy-web
    newName: ghcr.io/eduhamuy/eduhamuy-web
    newTag: f66328f71cd52fd3be945b6d42a22b5f0812ed27
