apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eduhamuy-dev

resources:
  - ../../../apps/eduhamuy-web/base
  - httproute.yaml
  - http-redirect.yaml

patches:
  - path: deployment-env.yaml

images:
  - name: ghcr.io/eduhamuy/eduhamuy-web
    newName: ghcr.io/eduhamuy/eduhamuy-web
    newTag: 82d09258c45174d434eebd8735207f9b895f8a42
