apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduhamuy-web
spec:
  template:
    spec:
      containers:
        - name: eduhamuy-web
          env:
            - name: EDUHAMUY_ENV
              value: "PROD"
            - name: LD_SDK_KEY
              valueFrom:
                secretKeyRef:
                  name: eduhamuy-launchdarkly
                  key: LD_SDK_KEY
            - name: AUTH_ENABLED
              value: "true"
            - name: AUTH_URL
              value: "https://eduhamuy.com"
            - name: AUTH_KEYCLOAK_ID
              value: "eduhamuy-web-prod"
            - name: AUTH_KEYCLOAK_ISSUER
              value: "https://keycloak-prod.eduhamuy.com/realms/eduhamuy-prod"
            - name: AUTH_KEYCLOAK_SECRET
              valueFrom:
                secretKeyRef:
                  name: eduhamuy-auth
                  key: AUTH_KEYCLOAK_SECRET
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: eduhamuy-auth
                  key: AUTH_SECRET
