apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eduhamuy-prod

resources:
  - ../../../apps/eduhamuy-web/base
  - httproute.yaml
  - http-redirect.yaml

patches:
  - path: deployment-env.yaml

images:
  - name: ghcr.io/eduhamuy/eduhamuy-web
    newName: ghcr.io/eduhamuy/eduhamuy-web
    newTag: 7fca09b7a2adc26edd08e4f3d2d8d0c25ff1118a
