apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eduhamuy-prod

resources:
  - ../../../apps/eduhamuy-web/base
  - httproute.yaml
  - http-redirect.yaml

patches:
  - path: deployment-env.yaml

images:
  - name: ghcr.io/eduhamuy/eduhamuy-web
    newName: ghcr.io/eduhamuy/eduhamuy-web
    newTag: 6302c5c23e4b2bff135b93b2272b52dfce86a368
