apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-operator
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: keycloak-operator
          env:
            - name: QUARKUS_OPERATOR_SDK_CONTROLLERS_KEYCLOAKREALMIMPORTCONTROLLER_NAMESPACES
              value: JOSDK_ALL_NAMESPACES
            - name: QUARKUS_OPERATOR_SDK_CONTROLLERS_KEYCLOAKSAMLCLIENTCONTROLLER_NAMESPACES
              value: JOSDK_ALL_NAMESPACES
            - name: QUARKUS_OPERATOR_SDK_CONTROLLERS_KEYCLOAKCONTROLLER_NAMESPACES
              value: JOSDK_ALL_NAMESPACES
            - name: QUARKUS_OPERATOR_SDK_CONTROLLERS_KEYCLOAKOIDCCLIENTCONTROLLER_NAMESPACES
              value: JOSDK_ALL_NAMESPACES
