apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eduhamuy-aio

resources:
  - ../../../apps/eduhamuy-web/base
  - ingress.yaml

patches:
  - path: deployment-env.yaml

images:
  - name: ghcr.io/eduhamuy/eduhamuy-web
    newName: ghcr.io/eduhamuy/eduhamuy-web
    newTag: 0e030ea3175b08f563b7145134f9ba878631d659
