apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: keycloak-prod
  namespace: argocd

spec:
  project: default

  source:
    repoURL: git@github.com:eduhamuy/eduhamuy-gitops.git
    targetRevision: main
    path: environments/prod/keycloak

  destination:
    server: https://kubernetes.default.svc
    namespace: eduhamuy-identity-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
