\getenv keycloak_password KEYCLOAK_DB_PASSWORD
CREATE ROLE keycloak LOGIN PASSWORD :'keycloak_password'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE keycloak OWNER keycloak ENCODING 'UTF8';
REVOKE ALL ON DATABASE keycloak FROM PUBLIC;
REVOKE CONNECT ON DATABASE postgres FROM PUBLIC;
REVOKE CONNECT ON DATABASE template1 FROM PUBLIC;
\connect keycloak
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
