apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eduhamuy-dev

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/eduhamuy/eduhamuy-ai
    newName: ghcr.io/eduhamuy/eduhamuy-ai
    newTag: b3f9c884a4770739363b32c467411195f2853d55
