apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eduhamuy-dev

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/eduhamuy/eduhamuy-ai
    newName: ghcr.io/eduhamuy/eduhamuy-ai
    newTag: bd1f749f757b38729d63284c4a733c833dbea01c
