apiVersion: v1
kind: Service
metadata:
  name: eduhamuy-ai
  labels:
    app: eduhamuy-ai
spec:
  type: ClusterIP
  selector:
    app: eduhamuy-ai
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
